site_name: Python, les fondamentaux
repo_url: https://github.com/darko-itpro/formation-Python_fondamentaux
plugins:
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - En français:
    - fr/index.md
    - Aides mémoire:
      - Les collections:
          - Les séquences: fr/memo/collections/sequences.md
          - Les listes: fr/memo/collections/listes.md
          - Chaines de caractères : fr/memo/collections/strings.md
          - Les dictionnaires: fr/memo/collections/dictionnaires.md
      - Les fonctions: fr/memo/fonctions.md
      - Structures de contrôle - les conditionnelles: fr/memo/conditionnelles.md
      - Structures de contrôle - les boucles: fr/memo/boucles.md
      - La Programmation Orientée Objet: fr/memo/poo.md
      - Les tests avec pytest:
          - fr/memo/tests/index.md
          - Aide mémoire sur les bases: fr/memo/tests/bases.md
          - Les tests paramétrés: fr/memo/tests/parametrized_tests.md
          - Les fixtures: fr/memo/tests/fixtures.md
    - Exercices:
        - fr/activities/index.md
        - Les bases:
          - Découverte du langage: fr/activities/discovery.md
          - Les listes (1): fr/activities/listes_1.md
          - Les conditionnelles (1): fr/activities/conditionnelles_1.md
          - Introduction aux fonctions: fr/activities/fonctions_introduction.md
          - Les conditionnelles (2): fr/activities/conditionnelles_2.md
          - Les dictionnaires: fr/activities/dictionnaires.md
          - Les listes (2): fr/activities/listes_2.md
          - Les exceptions (levée): fr/activities/exception_raise.md
          - Les exceptions (capture): fr/activities/exception_catch.md
          - Formatage des chaînes de caractères: fr/activities/strings.md
          - Les boucles: fr/activities/boucles.md
        - Plus spécialisé:
          - Les List Comprehension: fr/activities/list_comprehension.md
        - L'objet:
          - Notre modèle objet: fr/activities/modele_objet.md
    - Informations complémentaires:
        - Le package pyflix: fr/pyflix.md
        - Configuration du PYTHONPATH dans VSCode: fr/vscode.md
        - Les loggers: fr/memo/loggers.md

  - In English:
    - en/index.md

