site_name: Python, les fondamentaux
repo_url: https://github.com/darko-itpro/formation-Python_fondamentaux
plugins:
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - En français:
    - fr/index.md
    - Aides mémoire:
      - Les fonctions: fr/memo/fonctions.md
      - La Programmation Orientée Objet: fr/memo/poo.md
      - Les tests avec pytest:
          - fr/memo/tests/index.md
          - Aide mémoire sur les bases: fr/memo/tests/bases.md
          - Les tests paramétrés: fr/memo/tests/parametrized_tests.md
          - Les fixtures: fr/memo/tests/fixtures.md
      - Les loggers: fr/memo/loggers.md
    - Exercices:
        fr/activities/index.md
  - In English:
    - en/index.md

